/*
 * DATO MATRICE DI INTERI IN INPUT. SIA UN VALORE IN INGRESSO E VERIFICARE SE CI SIA NELLE RIGHE E COLONNE 
 * IL DOMINANTE, INDICANDONE ANCHE LA RELATIVA RIGA O COLONNA. IL DOMINANTE È QUANTO COMPARE IN TUTTE 
 * LE POSIZIONI DELLA RIGA O COLONNA.
 */
