/*
 * DATO IN INGRESSO UN VETTORE Di INTERI E SUA DIMENSIONE. SI CREI UNA FUNZIONE CHE CONTROLLI I VALORI DEL VETTORE.
 * A OGNI VALORE DISPARI SI CHIEDA IN INGRESSO UN NUOVO VALORE CHE SOSTITUIRA' IL VALORE DISPARI.
 * SI STAMPI INFINE IL VETTORE MODIFICATO.
 */
