/*
 * SIA DATO UN VETTORE DI INTERI E LA SUA DIMENSIONE IN INGRESSO.
 * CREARE UN NUOVO VETTORE DELLE STESSE DIMENSIONI DOVE MEMORIZZARE IN OGNI POSIZIONE
 * LE OCCORRENZE DEI NUMERI DEL PRIMO VETTORE.
 */
