/*
 * REALIZZARE UN PROGRAMMA PER IL CONTROLLO PASSWORD SICURA
 * DEVONO ESSERE SODDISFATTE LE SEGUENTI CONDIZIONI:
 * 1 - ALMENO DI 8 CARATTERI.
 * 2 - ALEMENO UN CARATTERE MINUSCOLO.
 * 3 - ALMENO UN CARATTERE MAIUSCOLO.
 * 4 - ALMENO UN NUMERO.
 * 5 - ALMENO UN CARATTERE SPECIALE.
 * UNA VOLTA VALIDATA LA PASSWORD VIENE RICHIESTO NUOVAMENTE L'INSERIMENTO DELLA MEDESIMA
 * SE LE PASSWORD NON SONO UGUALI E' NECESSARIA INSERIRE NUOVAMENTE LA PASSWORD DI CONTROLLO
 */
